### ISSUE TITLE
Not working with Dalli

### ISSUE THREAD

**Issue by jalberto** [alvesjtiago/fastentry#3]
Nice project :)

Just trying it noticed it doesn't work with `Dalli` gem.

`config.cache_store = :mem_cache_store, HOST], {compress: true, pool_size: 50, raise_errors: false }`

First I got an error about using a connection pool, but even when no connection pool is used I get this error:

`NoMethodError: undefined method `keys' for #<Dalli::Client:0x...>`

**Comment by alvesjtiago** [comment]
Thanks @jalberto!

Going to setup a demo project with `Dalli` to debug this.

**Comment by jalberto** [comment]
Thanks @alvesjtiago !

As far I know, `Dalli` is the most common client to use when using memcached, Rails uses it by default if the gem is installed, the same with `conection_pool`

**Comment by alvesjtiago** [comment]
@jalberto I've implemented a very experimental version that connects to Memcache and Dalli on version 0.1.12 (already pushed to rubygems). It would be great if you could give it a try and let me know if it works for you. Thanks!

**Comment by jalberto** [comment]
@alvesjtiago yay! it kind of works :)
Some key and values are displayed correctly, others seem encoded like

![screenshot from 2019-03-08 18-44-52](https://user-images.githubusercontent.com/99927/54045606-5b2b1b00-41d2-11e9-938c-07211d2f77f2.png)

**Comment by alvesjtiago** [comment]
Almost 😅

Just released version 0.1.13 with (hopefully) a fix. Let me know if it works 🤞

Thanks!

**Comment by jalberto** [comment]
@alvesjtiago now the keys looks better :) thanks!

**Comment by alvesjtiago** [comment]
@jalberto awesome! Going to close the issue. Let me know if there are any other problems you encounter.

Also it would be great to understand what are you using FastEntry for (ex. development debugging, production cache invalidation and inspection, etc). If you have time for a quick call or email chat, send me an email to tiago at rebase dot studio. Thanks again 😊
