### ISSUE TITLE
Redis.keys usage

### ISSUE THREAD

**Issue by ahmednaguib** [alvesjtiago/fastentry#4]
Thank you for this nice and useful project.

I was checking the `fastentry.rb` file and noticed the usage of `Redis.keys`
https://github.com/alvesjtiago/fastentry/blob/master/lib/fastentry.rb#L73

According to the official docs: https://redis.io/commands/keys

`Redis.keys` should be avoided on production environment especially for large redis databases.

One solution I can think of is to fetch the the first patch of keys. Then when displaying start paginating the rest of the keys.

**Comment by alvesjtiago** [comment]
Thank you so much @ahmednaguib.

You're absolutely right, I will add a note on the README file meanwhile to use FastEntry with redis only in development for now. After some tests locally with over 30k entries it has behaved well but we definitely need to handle this with care. When you mean fetch the first patch of keys how do you suggest performing this?

Once again thank you for your input and hopefully we can figure out the best possible solution together 😊

**Comment by ahmednaguib** [comment]
One way to paginate the keys retrieval is to use scan.
` redis.scan(0, count: per_page)`
This will return a cursor ( can be used in pagination), and array of N keys

But, this means in the dashboard controller, you won't get the full list. So, the logic of the pagination will need to change as well.

**Comment by alvesjtiago** [comment]
`dbsize` (https://github.com/redis/redis-rb/blob/df07a4c90413ed5dda7bc8fe928b00aaad5462fa/lib/redis.rb#L230) also seems to retrieve the total number of keys without actually fetching them. I will work on a PR to fix this when using redis. 

Thanks again @ahmednaguib. I'll let you know as soon as I've made some progress on this.

**Comment by alvesjtiago** [comment]
@ahmednaguib just released version 0.1.15 that addresses this issue. The commit that pertains to this is https://github.com/alvesjtiago/fastentry/commit/4181461fac4e63535d60d3bca3eb9a282ee66d6c. It would be great to get your feedback on this and once again thanks for raising the issue.

**Comment by ahmednaguib** [comment]
@alvesjtiago Awesome job :+1:
