### ISSUE TITLE
Fails in a Proxy

### ISSUE THREAD

**Issue by joelmoss** [alvesjtiago/fastentry#5]
So I have a simple Rack proxy in my Rails app that simply proxies certain requests...

```ruby
require 'rack/proxy'

class Webpack::DevServerProxy < Rack::Proxy
  def perform_request(env)
    # does something here...

    @app.call(env)
  end
end
```

Running Fastentry results in an `ArgumentError` exception: `Unsupported cache type` on `@app.call(env)`.

Any ideas? thx

**Comment by alvesjtiago** [comment]
Hi @joelmoss, thanks for reporting that issue. I'll try to setup an app with a proxy to investigate what might be the issue. In the meantime, if you figure out what's the problem, please let me know.

**Comment by alvesjtiago** [comment]
@joelmoss in order for me to accurately test what might be wrong, can you tell me what cache type are you using on your app? Thanks

**Comment by alvesjtiago** [comment]
@joelmoss in order for me to accurately test what might be wrong, can you tell me what cache type are you using on your app? Thanks

**Comment by alvesjtiago** [comment]
I've tested it with `rack_proxy_examples/example_service_proxy` and it seems to work just fine so it's probably something else.

**Comment by joelmoss** [comment]
hmm, will dig a little further. thx

**Comment by alvesjtiago** [comment]
@joelmoss closing for now but let me know if you still have any issues. Thanks
