### ISSUE TITLE
Redis ERR syntax error if no cache keys exists

### ISSUE THREAD

**Issue by satetsu888** [alvesjtiago/fastentry#8]
An error occurs when getting access dashboard controller with no cache keys exists using redis cache.

In detail,  `adjusted_amount` returns `0` when no cache keys exists.
Then redis command `SCAN 0 COUNT 0` is processed and `Redis::CommandError` thrown.

https://github.com/alvesjtiago/fastentry/blob/7f4d69009c775a209797ad50cd0a63317b9676a6/lib/fastentry.rb#L99-L102

We need to adjust count to always greater than 0  if using redis cache?

My environment
- Redis server 5.0.7
- Rails 5.2.3

**Comment by alvesjtiago** [comment]
Thank you for reporting this @satetsu888, I’ll believe you’re right. I’m going to make sure that is the case and fix the issue.

**Comment by alvesjtiago** [comment]
Version 0.1.16 that was just published on RubyGems should address this issue. Once again thank you for reporting it. I'm going to close the issue but if you continue to have issues please let me know.
